export const theme = {
  colors: {
    background: '#F3EEE4',
    backgroundAccent: '#E6DED0',
    surface: '#FFFCF7',
    surfaceMuted: '#F6F0E7',
    border: '#D7CCBD',
    primary: '#1D3657',
    primarySoft: '#D9E4F1',
    accent: '#B88746',
    accentSoft: '#F5E8D6',
    success: '#2F6B4F',
    successSoft: '#E0F0E6',
    warning: '#8C5A21',
    warningSoft: '#F6E7D4',
    danger: '#8E3B2F',
    dangerSoft: '#F5DDD8',
    text: '#1F1D1A',
    textMuted: '#6B655D',
    white: '#FFFFFF',
  },
  spacing: {
    xs: 6,
    sm: 10,
    md: 16,
    lg: 20,
    xl: 28,
  },
  radius: {
    sm: 10,
    md: 16,
    lg: 24,
    pill: 999,
  },
  typography: {
    heading: 'SourceSerif4_600SemiBold',
    headingBold: 'SourceSerif4_700Bold',
    body: 'Manrope_500Medium',
    bodySemiBold: 'Manrope_600SemiBold',
    bodyBold: 'Manrope_700Bold',
  },
} as const;
